name: Build
on:
    push:
        branches:
            -  main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: acifani/setup-tinygo@v1
          with:
            tinygo-version: 0.27.0
        - run: pip install yq
        - run: BUILDCMD=$(cat spin.toml | tomlq -r '.component[0].build.command') && eval $BUILDCMD